# Generated by Django 4.2.5 on 2023-09-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(),
        ),
    ]
